// Code generated by gs-mock v0.0.5. DO NOT EDIT.
// Source: https://github.com/go-spring/gs-mock
// gs mock -o app_mock.go -i 'Server'

package gs_app

import (
	"context"
	"github.com/go-spring/gs-mock/gsmock"
	"reflect"
)

// ServerMockImpl is a generated mock implementation of the Server interface.
// It embeds the original interfaces and provides methods to register mock behaviors.
type ServerMockImpl struct {
	r *gsmock.Manager
}

// NewServerMockImpl creates a new mock instance for Server with the given
// gsmock.Manager and initializes the embedded interfaces.
func NewServerMockImpl(r *gsmock.Manager) *ServerMockImpl {
	return &ServerMockImpl{r: r}
}

// ListenAndServe executes the mocked ListenAndServe method.
// with 2 parameters and 1 return values.
func (impl *ServerMockImpl) ListenAndServe(ctx context.Context, sig ReadySignal) error {
	t := reflect.TypeFor[ServerMockImpl]()
	if ret, ok := gsmock.Invoke(impl.r, t, "ListenAndServe", ctx, sig); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for Server.ListenAndServe")
}

// MockListenAndServe returns a MockerNN instance to register mock behavior for ListenAndServe.
func (impl *ServerMockImpl) MockListenAndServe() *gsmock.Mocker21[context.Context, ReadySignal, error] {
	t := reflect.TypeFor[ServerMockImpl]()
	return gsmock.NewMocker21[context.Context, ReadySignal, error](impl.r, t, "ListenAndServe")
}

// Shutdown executes the mocked Shutdown method.
// with 1 parameters and 1 return values.
func (impl *ServerMockImpl) Shutdown(ctx context.Context) error {
	t := reflect.TypeFor[ServerMockImpl]()
	if ret, ok := gsmock.Invoke(impl.r, t, "Shutdown", ctx); ok {
		return gsmock.Unbox1[error](ret)
	}
	panic("no mock code matched for Server.Shutdown")
}

// MockShutdown returns a MockerNN instance to register mock behavior for Shutdown.
func (impl *ServerMockImpl) MockShutdown() *gsmock.Mocker11[context.Context, error] {
	t := reflect.TypeFor[ServerMockImpl]()
	return gsmock.NewMocker11[context.Context, error](impl.r, t, "Shutdown")
}
